
#footprint: [[ 0.175,  0.175],
#            [-0.175,  0.175],
#            [-0.175, -0.175],
#            [ 0.175, -0.175]]
#inflation_radius: 0.05

footprint: [[ 0.1,  0.1],
            [-0.1,  0.1],
            [-0.1, -0.1],
            [ 0.1, -0.1]]
inflation_radius: 0.05

observation_sources: laser_scan_sensor 
laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true, obstacle_range: 2.0, raytrace_range: 2}

