controller_frequency: 20.0
controller_patience:  15.0
planner_frequency: 0
oscillation_distance: 0.3
planner_patience:  5.0
footprint_padding: 0.01
base_global_planner: navfn/NavfnROS
base_local_planner: dwa_local_planner/DWAPlannerROS
recovery_behavior_enabled: true


