TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.05
  max_vel_theta: 0.2
  min_vel_theta: -0.1
  min_in_place_vel_theta: 0.05
  max_rotational_vel: 0.2
  min_in_place_rotational_vel: 0.05

  acc_lim_th: 0.4
  acc_lim_x: 1.5
  acc_lim_y: 0.0

  holonomic_robot: false

  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

  dwa: false

  heading_lookahead: 0.5

  publish_cost_grid_pc: false

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.5

  oscillation_reset_dist: 0.3
